FileVersion = 1
Dependencies = {corlib = "*", corlib = "*"}

[Project]
Name = "BeefRaylibBindings"
TargetType = "BeefLib"
StartupObject = "Raylib.Program"
DefaultNamespace = "Raylib"

[Configs.Debug.Win64]
CLibType = "Static"
LibPaths = ["$(ProjectDir)/lib/raylib.lib"]
