FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", corlib = "*"}

[Project]
Name = "BeefRaylibBindings"
TargetType = "BeefLib"
StartupObject = "Raylib.Program"
DefaultNamespace = "Raylib"

[Configs.Debug.Win64]
CLibType = "Static"
LibPaths = ["$(ProjectDir)/lib/raylib.lib", "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/WinMM.lib", "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/Gdi32.lib", "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/User32.lib", "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.19041.0/um/x64/Shell32.lib"]

[[ProjectFolder.Items]]
Type = "IgnoreFolder"
Name = "Examples"
AutoInclude = true
